{{- if .Values.configVolume.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configName }}
type: Opaque
data:
  config.ini: {{ .Values.configVolume.data | b64enc | quote }}
{{- end -}}
